openapi: 3.0.3
info:
  title: 'Products API'
  description: 'This is a simple API for a products catalog.'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/login:
    post:
      summary: 'Login the user'
      operationId: loginTheUser
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  token: 1|0M0VCKSJam4zQU058p3ZJ4GXCiDCWYkCyJflPegA
                  user:
                    id: 1
                    name: 'John Doe'
                    email: johndoe@example.com
                properties:
                  token:
                    type: string
                    example: 1|0M0VCKSJam4zQU058p3ZJ4GXCiDCWYkCyJflPegA
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: 'John Doe'
                      email:
                        type: string
                        example: johndoe@example.com
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'The Email of the user.'
                  example: user@example.com
                password:
                  type: string
                  description: 'The password of the user.'
                  example: password
              required:
                - email
                - password
      security: []
  /api/logout:
    post:
      summary: 'Logout the user'
      operationId: logoutTheUser
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - Authentication
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 1
                  name: 'Test User'
                  email: test@example.com
                  email_verified_at: '2023-04-23T12:31:40.000000Z'
                  created_at: '2023-04-23T12:31:40.000000Z'
                  updated_at: '2023-04-23T12:31:40.000000Z'
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: 'Test User'
                  email:
                    type: string
                    example: test@example.com
                  email_verified_at:
                    type: string
                    example: '2023-04-23T12:31:40.000000Z'
                  created_at:
                    type: string
                    example: '2023-04-23T12:31:40.000000Z'
                  updated_at:
                    type: string
                    example: '2023-04-23T12:31:40.000000Z'
      tags:
        - Endpoints
  /api/health-check:
    get:
      summary: ''
      operationId: getApiHealthCheck
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: up
                  services:
                    database: up
                    redis: up
                properties:
                  status:
                    type: string
                    example: up
                  services:
                    type: object
                    properties:
                      database:
                        type: string
                        example: up
                      redis:
                        type: string
                        example: up
      tags:
        - Endpoints
  /api/collection:
    get:
      summary: ''
      operationId: getApiCollection
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  '1':
                    name: Chair
                    price: 100
                  '3':
                    name: Door
                    price: 100
                properties:
                  1:
                    type: object
                    properties:
                      name:
                        type: string
                        example: Chair
                      price:
                        type: integer
                        example: 100
                  3:
                    type: object
                    properties:
                      name:
                        type: string
                        example: Door
                      price:
                        type: integer
                        example: 100
      tags:
        - Endpoints
  /api/products:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data: []
                properties:
                  data:
                    type: array
                    example: []
      tags:
        - Products
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'The name of the product. Must not be greater than 255 characters.'
                  example: 'Product name'
                description:
                  type: string
                  description: 'The description of the product.'
                  example: 'Product description'
                price:
                  type: string
                  description: 'The price of the product.'
                  example: 100
                is_active:
                  type: boolean
                  description: 'The status of the product.'
                  example: false
                cover_image:
                  type: string
                  description: 'The cover image of the product.'
                  example: 'https://example.com/image.jpg'
              required:
                - name
                - price
                - is_active
                - cover_image
  '/api/products/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No query results for model [App\Models\Product] culpa'
                  exception: Symfony\Component\HttpKernel\Exception\NotFoundHttpException
                  file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php
                  line: 408
                  trace:
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php
                      line: 384
                      function: prepareException
                      class: Illuminate\Foundation\Exceptions\Handler
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php
                      line: 54
                      function: render
                      class: Illuminate\Foundation\Exceptions\Handler
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
                      line: 51
                      function: render
                      class: NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                      line: 185
                      function: handleException
                      class: Illuminate\Routing\Pipeline
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php
                      line: 126
                      function: 'Illuminate\Pipeline\{closure}'
                      class: Illuminate\Pipeline\Pipeline
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php
                      line: 102
                      function: handleRequest
                      class: Illuminate\Routing\Middleware\ThrottleRequests
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php
                      line: 54
                      function: handleRequestUsingNamedLimiter
                      class: Illuminate\Routing\Middleware\ThrottleRequests
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                      line: 180
                      function: handle
                      class: Illuminate\Routing\Middleware\ThrottleRequests
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php
                      line: 45
                      function: 'Illuminate\Pipeline\{closure}'
                      class: Illuminate\Pipeline\Pipeline
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                      line: 180
                      function: handle
                      class: Illuminate\Auth\Middleware\Authenticate
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                      line: 116
                      function: 'Illuminate\Pipeline\{closure}'
                      class: Illuminate\Pipeline\Pipeline
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Routing/Router.php
                      line: 799
                      function: then
                      class: Illuminate\Pipeline\Pipeline
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Routing/Router.php
                      line: 776
                      function: runRouteWithinStack
                      class: Illuminate\Routing\Router
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Routing/Router.php
                      line: 740
                      function: runRoute
                      class: Illuminate\Routing\Router
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Routing/Router.php
                      line: 729
                      function: dispatchToRoute
                      class: Illuminate\Routing\Router
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php
                      line: 200
                      function: dispatch
                      class: Illuminate\Routing\Router
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                      line: 141
                      function: 'Illuminate\Foundation\Http\{closure}'
                      class: Illuminate\Foundation\Http\Kernel
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php
                      line: 21
                      function: 'Illuminate\Pipeline\{closure}'
                      class: Illuminate\Pipeline\Pipeline
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php
                      line: 31
                      function: handle
                      class: Illuminate\Foundation\Http\Middleware\TransformsRequest
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                      line: 180
                      function: handle
                      class: Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php
                      line: 21
                      function: 'Illuminate\Pipeline\{closure}'
                      class: Illuminate\Pipeline\Pipeline
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php
                      line: 40
                      function: handle
                      class: Illuminate\Foundation\Http\Middleware\TransformsRequest
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                      line: 180
                      function: handle
                      class: Illuminate\Foundation\Http\Middleware\TrimStrings
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php
                      line: 27
                      function: 'Illuminate\Pipeline\{closure}'
                      class: Illuminate\Pipeline\Pipeline
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                      line: 180
                      function: handle
                      class: Illuminate\Foundation\Http\Middleware\ValidatePostSize
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php
                      line: 86
                      function: 'Illuminate\Pipeline\{closure}'
                      class: Illuminate\Pipeline\Pipeline
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                      line: 180
                      function: handle
                      class: Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php
                      line: 62
                      function: 'Illuminate\Pipeline\{closure}'
                      class: Illuminate\Pipeline\Pipeline
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                      line: 180
                      function: handle
                      class: Illuminate\Http\Middleware\HandleCors
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php
                      line: 39
                      function: 'Illuminate\Pipeline\{closure}'
                      class: Illuminate\Pipeline\Pipeline
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                      line: 180
                      function: handle
                      class: Illuminate\Http\Middleware\TrustProxies
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                      line: 116
                      function: 'Illuminate\Pipeline\{closure}'
                      class: Illuminate\Pipeline\Pipeline
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php
                      line: 175
                      function: then
                      class: Illuminate\Pipeline\Pipeline
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php
                      line: 144
                      function: sendRequestThroughRouter
                      class: Illuminate\Foundation\Http\Kernel
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/Extracting/Strategies/Responses/ResponseCalls.php
                      line: 299
                      function: handle
                      class: Illuminate\Foundation\Http\Kernel
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/Extracting/Strategies/Responses/ResponseCalls.php
                      line: 287
                      function: callLaravelOrLumenRoute
                      class: Knuckles\Scribe\Extracting\Strategies\Responses\ResponseCalls
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/Extracting/Strategies/Responses/ResponseCalls.php
                      line: 92
                      function: makeApiCall
                      class: Knuckles\Scribe\Extracting\Strategies\Responses\ResponseCalls
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/Extracting/Strategies/Responses/ResponseCalls.php
                      line: 45
                      function: makeResponseCall
                      class: Knuckles\Scribe\Extracting\Strategies\Responses\ResponseCalls
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/Extracting/Strategies/Responses/ResponseCalls.php
                      line: 35
                      function: makeResponseCallIfConditionsPass
                      class: Knuckles\Scribe\Extracting\Strategies\Responses\ResponseCalls
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/Extracting/Extractor.php
                      line: 209
                      function: __invoke
                      class: Knuckles\Scribe\Extracting\Strategies\Responses\ResponseCalls
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/Extracting/Extractor.php
                      line: 166
                      function: iterateThroughStrategies
                      class: Knuckles\Scribe\Extracting\Extractor
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/Extracting/Extractor.php
                      line: 95
                      function: fetchResponses
                      class: Knuckles\Scribe\Extracting\Extractor
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/GroupedEndpoints/GroupedEndpointsFromApp.php
                      line: 124
                      function: processRoute
                      class: Knuckles\Scribe\Extracting\Extractor
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/GroupedEndpoints/GroupedEndpointsFromApp.php
                      line: 71
                      function: extractEndpointsInfoFromLaravelApp
                      class: Knuckles\Scribe\GroupedEndpoints\GroupedEndpointsFromApp
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/GroupedEndpoints/GroupedEndpointsFromApp.php
                      line: 49
                      function: extractEndpointsInfoAndWriteToDisk
                      class: Knuckles\Scribe\GroupedEndpoints\GroupedEndpointsFromApp
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/Commands/GenerateDocumentation.php
                      line: 51
                      function: get
                      class: Knuckles\Scribe\GroupedEndpoints\GroupedEndpointsFromApp
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php
                      line: 36
                      function: handle
                      class: Knuckles\Scribe\Commands\GenerateDocumentation
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Container/Util.php
                      line: 41
                      function: 'Illuminate\Container\{closure}'
                      class: Illuminate\Container\BoundMethod
                      type: '::'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php
                      line: 93
                      function: unwrapIfClosure
                      class: Illuminate\Container\Util
                      type: '::'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php
                      line: 37
                      function: callBoundMethod
                      class: Illuminate\Container\BoundMethod
                      type: '::'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Container/Container.php
                      line: 662
                      function: call
                      class: Illuminate\Container\BoundMethod
                      type: '::'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Console/Command.php
                      line: 194
                      function: call
                      class: Illuminate\Container\Container
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/symfony/console/Command/Command.php
                      line: 312
                      function: execute
                      class: Illuminate\Console\Command
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Console/Command.php
                      line: 164
                      function: run
                      class: Symfony\Component\Console\Command\Command
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/symfony/console/Application.php
                      line: 1040
                      function: run
                      class: Illuminate\Console\Command
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/symfony/console/Application.php
                      line: 314
                      function: doRunCommand
                      class: Symfony\Component\Console\Application
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/symfony/console/Application.php
                      line: 168
                      function: doRun
                      class: Symfony\Component\Console\Application
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php
                      line: 200
                      function: run
                      class: Symfony\Component\Console\Application
                      type: '->'
                    -
                      file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/artisan
                      line: 37
                      function: handle
                      class: Illuminate\Foundation\Console\Kernel
                      type: '->'
                properties:
                  message:
                    type: string
                    example: 'No query results for model [App\Models\Product] culpa'
                  exception:
                    type: string
                    example: Symfony\Component\HttpKernel\Exception\NotFoundHttpException
                  file:
                    type: string
                    example: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php
                  line:
                    type: integer
                    example: 408
                  trace:
                    type: array
                    example:
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php
                        line: 384
                        function: prepareException
                        class: Illuminate\Foundation\Exceptions\Handler
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php
                        line: 54
                        function: render
                        class: Illuminate\Foundation\Exceptions\Handler
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
                        line: 51
                        function: render
                        class: NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                        line: 185
                        function: handleException
                        class: Illuminate\Routing\Pipeline
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php
                        line: 126
                        function: 'Illuminate\Pipeline\{closure}'
                        class: Illuminate\Pipeline\Pipeline
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php
                        line: 102
                        function: handleRequest
                        class: Illuminate\Routing\Middleware\ThrottleRequests
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php
                        line: 54
                        function: handleRequestUsingNamedLimiter
                        class: Illuminate\Routing\Middleware\ThrottleRequests
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                        line: 180
                        function: handle
                        class: Illuminate\Routing\Middleware\ThrottleRequests
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php
                        line: 45
                        function: 'Illuminate\Pipeline\{closure}'
                        class: Illuminate\Pipeline\Pipeline
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                        line: 180
                        function: handle
                        class: Illuminate\Auth\Middleware\Authenticate
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                        line: 116
                        function: 'Illuminate\Pipeline\{closure}'
                        class: Illuminate\Pipeline\Pipeline
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Routing/Router.php
                        line: 799
                        function: then
                        class: Illuminate\Pipeline\Pipeline
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Routing/Router.php
                        line: 776
                        function: runRouteWithinStack
                        class: Illuminate\Routing\Router
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Routing/Router.php
                        line: 740
                        function: runRoute
                        class: Illuminate\Routing\Router
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Routing/Router.php
                        line: 729
                        function: dispatchToRoute
                        class: Illuminate\Routing\Router
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php
                        line: 200
                        function: dispatch
                        class: Illuminate\Routing\Router
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                        line: 141
                        function: 'Illuminate\Foundation\Http\{closure}'
                        class: Illuminate\Foundation\Http\Kernel
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php
                        line: 21
                        function: 'Illuminate\Pipeline\{closure}'
                        class: Illuminate\Pipeline\Pipeline
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php
                        line: 31
                        function: handle
                        class: Illuminate\Foundation\Http\Middleware\TransformsRequest
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                        line: 180
                        function: handle
                        class: Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php
                        line: 21
                        function: 'Illuminate\Pipeline\{closure}'
                        class: Illuminate\Pipeline\Pipeline
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php
                        line: 40
                        function: handle
                        class: Illuminate\Foundation\Http\Middleware\TransformsRequest
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                        line: 180
                        function: handle
                        class: Illuminate\Foundation\Http\Middleware\TrimStrings
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php
                        line: 27
                        function: 'Illuminate\Pipeline\{closure}'
                        class: Illuminate\Pipeline\Pipeline
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                        line: 180
                        function: handle
                        class: Illuminate\Foundation\Http\Middleware\ValidatePostSize
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php
                        line: 86
                        function: 'Illuminate\Pipeline\{closure}'
                        class: Illuminate\Pipeline\Pipeline
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                        line: 180
                        function: handle
                        class: Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php
                        line: 62
                        function: 'Illuminate\Pipeline\{closure}'
                        class: Illuminate\Pipeline\Pipeline
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                        line: 180
                        function: handle
                        class: Illuminate\Http\Middleware\HandleCors
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php
                        line: 39
                        function: 'Illuminate\Pipeline\{closure}'
                        class: Illuminate\Pipeline\Pipeline
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                        line: 180
                        function: handle
                        class: Illuminate\Http\Middleware\TrustProxies
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
                        line: 116
                        function: 'Illuminate\Pipeline\{closure}'
                        class: Illuminate\Pipeline\Pipeline
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php
                        line: 175
                        function: then
                        class: Illuminate\Pipeline\Pipeline
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php
                        line: 144
                        function: sendRequestThroughRouter
                        class: Illuminate\Foundation\Http\Kernel
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/Extracting/Strategies/Responses/ResponseCalls.php
                        line: 299
                        function: handle
                        class: Illuminate\Foundation\Http\Kernel
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/Extracting/Strategies/Responses/ResponseCalls.php
                        line: 287
                        function: callLaravelOrLumenRoute
                        class: Knuckles\Scribe\Extracting\Strategies\Responses\ResponseCalls
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/Extracting/Strategies/Responses/ResponseCalls.php
                        line: 92
                        function: makeApiCall
                        class: Knuckles\Scribe\Extracting\Strategies\Responses\ResponseCalls
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/Extracting/Strategies/Responses/ResponseCalls.php
                        line: 45
                        function: makeResponseCall
                        class: Knuckles\Scribe\Extracting\Strategies\Responses\ResponseCalls
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/Extracting/Strategies/Responses/ResponseCalls.php
                        line: 35
                        function: makeResponseCallIfConditionsPass
                        class: Knuckles\Scribe\Extracting\Strategies\Responses\ResponseCalls
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/Extracting/Extractor.php
                        line: 209
                        function: __invoke
                        class: Knuckles\Scribe\Extracting\Strategies\Responses\ResponseCalls
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/Extracting/Extractor.php
                        line: 166
                        function: iterateThroughStrategies
                        class: Knuckles\Scribe\Extracting\Extractor
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/Extracting/Extractor.php
                        line: 95
                        function: fetchResponses
                        class: Knuckles\Scribe\Extracting\Extractor
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/GroupedEndpoints/GroupedEndpointsFromApp.php
                        line: 124
                        function: processRoute
                        class: Knuckles\Scribe\Extracting\Extractor
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/GroupedEndpoints/GroupedEndpointsFromApp.php
                        line: 71
                        function: extractEndpointsInfoFromLaravelApp
                        class: Knuckles\Scribe\GroupedEndpoints\GroupedEndpointsFromApp
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/GroupedEndpoints/GroupedEndpointsFromApp.php
                        line: 49
                        function: extractEndpointsInfoAndWriteToDisk
                        class: Knuckles\Scribe\GroupedEndpoints\GroupedEndpointsFromApp
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/knuckleswtf/scribe/src/Commands/GenerateDocumentation.php
                        line: 51
                        function: get
                        class: Knuckles\Scribe\GroupedEndpoints\GroupedEndpointsFromApp
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php
                        line: 36
                        function: handle
                        class: Knuckles\Scribe\Commands\GenerateDocumentation
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Container/Util.php
                        line: 41
                        function: 'Illuminate\Container\{closure}'
                        class: Illuminate\Container\BoundMethod
                        type: '::'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php
                        line: 93
                        function: unwrapIfClosure
                        class: Illuminate\Container\Util
                        type: '::'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php
                        line: 37
                        function: callBoundMethod
                        class: Illuminate\Container\BoundMethod
                        type: '::'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Container/Container.php
                        line: 662
                        function: call
                        class: Illuminate\Container\BoundMethod
                        type: '::'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Console/Command.php
                        line: 194
                        function: call
                        class: Illuminate\Container\Container
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/symfony/console/Command/Command.php
                        line: 312
                        function: execute
                        class: Illuminate\Console\Command
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Console/Command.php
                        line: 164
                        function: run
                        class: Symfony\Component\Console\Command\Command
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/symfony/console/Application.php
                        line: 1040
                        function: run
                        class: Illuminate\Console\Command
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/symfony/console/Application.php
                        line: 314
                        function: doRunCommand
                        class: Symfony\Component\Console\Application
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/symfony/console/Application.php
                        line: 168
                        function: doRun
                        class: Symfony\Component\Console\Application
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php
                        line: 200
                        function: run
                        class: Symfony\Component\Console\Application
                        type: '->'
                      -
                        file: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/artisan
                        line: 37
                        function: handle
                        class: Illuminate\Foundation\Console\Kernel
                        type: '->'
                    items:
                      type: object
                      properties:
                        file:
                          type: string
                          example: /Users/alpha/Documents/GitHub/alphaolomi/laravel-api-docs/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php
                        line:
                          type: integer
                          example: 384
                        function:
                          type: string
                          example: prepareException
                        class:
                          type: string
                          example: Illuminate\Foundation\Exceptions\Handler
                        type:
                          type: string
                          example: '->'
      tags:
        - Products
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'The name of the product. Must not be greater than 255 characters.'
                  example: 'Product name'
                description:
                  type: string
                  description: 'The description of the product.'
                  example: 'Product description'
                price:
                  type: string
                  description: 'The price of the product.'
                  example: 100
                is_active:
                  type: boolean
                  description: 'The status of the product.'
                  example: false
                cover_image:
                  type: string
                  description: 'The cover image of the product.'
                  example: 'https://example.com/image.jpg'
              required:
                - name
                - price
                - is_active
                - cover_image
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - Products
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: culpa
        required: true
        schema:
          type: string
tags:
  -
    name: Authentication
    description: 'APIs for authentication'
  -
    name: Endpoints
    description: ''
  -
    name: Products
    description: 'APIs for products'
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
